name: Basic run unit tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest, windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: 
          python -m unittest testRectangle.py
          python -m unittest testSquare.py
          python -m unittest testTriangle.py
          python -m unittest testCircle.py
