name: Basic run unit tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
      strategy:
        matrix:
          os: [ubuntu-latest,windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Run unit tests
          run: 
            python -m unittest TestCircle.py
            python -m unittest TestRectangle.py
            python -m unittest TestTriangle.py
            python -m unittest TestSquare.py
