name: CI/CD

on:
  push:
    branches:
      - main
      - tests_341110
  pull_request:
    branches:
      - main
      - tests_341110

jobs:
  tests-for-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Run tests
        run: |
          python -m unittest "circle_tests.py"
          python -m unittest "rectangle_tests.py"
          python -m unittest "square_tests.py"
          python -m unittest "triangle_tests.py"
  tests-for-windows:
    runs-on: windows-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3
      - name: Install python for check
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Run tests
        run: |
          python -m unittest "circle_tests.py"
          python -m unittest "rectangle_tests.py"
          python -m unittest "square_tests.py"
          python -m unittest "triangle_tests.py"
