name: test functions

on:
  push:
    branches: 
	    - cicd_408876

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - name: ubuntu check
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run python unit tests
        run: |
          python3 -m unittest test_circle
          python3 -m unittest test_rectangle
          python3 -m unittest test_square
          python3 -m unittest test_triangle

  test_windows:
    runs-on: windows-latest

    steps:
      - name: windows check
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run python unit tests
        run: |
          python3 -m unittest test_circle
          python3 -m unittest test_rectangle
          python3 -m unittest test_square
          python3 -m unittest test_triangle