name: Ci
on:
  push:
    branches:
      - cicd_337004
  pull_request:
    branches:
      - cicd_337004
permissions:
  contents: read
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: tests run
        run: python -m unittest tests.py
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: tests run
        run: python -m unittest tests.py